version: '2'
services:
    kepegawaian-app:
        image: kepegawaian
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kepegawaian-mysql:3306/kepegawaian?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8077:8077
    kepegawaian-mysql:
        extends:
            file: mysql.yml
            service: kepegawaian-mysql
